# Generated by Django 4.0.2 on 2022-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activitycompany_categoryrequisite_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetails',
            name='bin',
            field=models.CharField(blank=True, max_length=200, verbose_name='БИН'),
        ),
        migrations.AlterField(
            model_name='companybankdetails',
            name='rnn',
            field=models.CharField(blank=True, max_length=200, verbose_name='РНН'),
        ),
    ]
