# Generated by Django 4.0.2 on 2022-10-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_companybankdetails_bin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyrequisite',
            options={'verbose_name': 'Реквизит компании', 'verbose_name_plural': '2.8) Реквизиты компании'},
        ),
        migrations.RemoveField(
            model_name='companyaddress',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='companyaddress',
            name='street',
        ),
        migrations.RemoveField(
            model_name='companyrequisite',
            name='type',
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица, дом, квартира'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='person',
            field=models.CharField(blank=True, max_length=250, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Моб. телефон'),
        ),
        migrations.AddField(
            model_name='companyrequisite',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.categoryrequisite', verbose_name='Категория (Реквезиты)'),
        ),
        migrations.AddField(
            model_name='companyrequisite',
            name='value',
            field=models.CharField(blank=True, max_length=200, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Моб. телефон'),
        ),
        migrations.DeleteModel(
            name='RequisiteField',
        ),
    ]
