# Generated by Django 4.0.2 on 2022-10-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_companyrequisite_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybankdetails',
            name='acc_currency',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='cor_acc',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='title',
        ),
    ]
