# Generated by Django 4.0.2 on 2022-10-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_companybankdetails_acc_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybankdetails',
            name='swift',
        ),
    ]
