# Generated by Django 4.0.2 on 2022-10-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_companybankdetails_swift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryrequisite',
            name='pe',
        ),
    ]
