# Generated by Django 4.0.2 on 2022-10-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_useraddress_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybankdetails',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='companybankdetails',
            name='rnn',
        ),
    ]
