# Generated by Django 4.0.2 on 2022-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_companybankdetails_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='company',
            name='iin_bin',
            field=models.CharField(blank=True, max_length=200, verbose_name='БИН/ИИН'),
        ),
        migrations.AddField(
            model_name='company',
            name='kbe',
            field=models.CharField(blank=True, max_length=200, verbose_name='КБе'),
        ),
        migrations.AddField(
            model_name='company',
            name='nds',
            field=models.CharField(blank=True, max_length=200, verbose_name='НДС'),
        ),
    ]
