# Generated by Django 4.0.2 on 2022-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_company_address_company_iin_bin_company_kbe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='for_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Анонимный пользователь'),
        ),
    ]
