# Generated by Django 4.0.2 on 2022-10-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_companycontact_for_anonymous_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='iin_bin',
            field=models.CharField(max_length=200, verbose_name='БИН/ИИН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='companybankdetails',
            name='bank_title',
            field=models.CharField(max_length=200, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='companybankdetails',
            name='bik',
            field=models.CharField(max_length=200, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='companybankdetails',
            name='iik',
            field=models.CharField(max_length=200, verbose_name='ИИК'),
        ),
    ]
