# Generated by Django 4.0.2 on 2022-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_company_address_alter_company_iin_bin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Моб. телефон'),
        ),
    ]
