# Generated by Django 4.0.2 on 2022-02-21 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('order', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы)')),
                ('order_realization', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы под реализацию)')),
                ('refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Возврат)')),
                ('stocks', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Акции)')),
                ('order_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы)')),
                ('order_realization_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы под реализацию)')),
                ('refund_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Возврат)')),
                ('stocks_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Акции)')),
            ],
            options={
                'verbose_name': 'Статистика за день',
                'verbose_name_plural': 'Статистика за день',
            },
        ),
        migrations.CreateModel(
            name='ForMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('order', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы)')),
                ('order_realization', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы под реализацию)')),
                ('refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Возврат)')),
                ('stocks', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Акции)')),
                ('order_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы)')),
                ('order_realization_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы под реализацию)')),
                ('refund_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Возврат)')),
                ('stocks_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Акции)')),
            ],
            options={
                'verbose_name': 'Статистика за месяц',
                'verbose_name_plural': 'Статистика за месяц',
            },
        ),
        migrations.CreateModel(
            name='ForYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('order', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы)')),
                ('order_realization', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы под реализацию)')),
                ('refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Возврат)')),
                ('stocks', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Акции)')),
                ('order_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы)')),
                ('order_realization_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы под реализацию)')),
                ('refund_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Возврат)')),
                ('stocks_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Акции)')),
            ],
            options={
                'verbose_name': 'Статистика за год',
                'verbose_name_plural': 'Статистика за год',
            },
        ),
    ]
