# Generated by Django 4.0.2 on 2022-02-24 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_statistics', '0002_forday_order_debt_forday_order_realization_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('order', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы)')),
                ('order_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма долга (Заказы)')),
                ('order_realization', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Заказы под реализацию)')),
                ('order_realization_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма долга (Заказы под реализацию)')),
                ('refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Возврат)')),
                ('stocks', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Общая сумма (Акции)')),
                ('order_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы)')),
                ('order_realization_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Заказы под реализацию)')),
                ('refund_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Возврат)')),
                ('stocks_qty', models.PositiveIntegerField(default=0, verbose_name='Количество (Акции)')),
            ],
            options={
                'verbose_name': 'Статистика за неделю',
                'verbose_name_plural': 'Статистика за неделю',
            },
        ),
    ]
