# Generated by Django 4.0.2 on 2022-02-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_statistics', '0003_forweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='forday',
            name='week_day',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='День недели'),
        ),
    ]
