# Generated by Django 4.0.2 on 2022-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_statistics', '0004_forday_week_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForMonth',
        ),
        migrations.DeleteModel(
            name='ForWeek',
        ),
        migrations.DeleteModel(
            name='ForYear',
        ),
        migrations.RemoveField(
            model_name='forday',
            name='week_day',
        ),
        migrations.AddField(
            model_name='forday',
            name='order_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма наличными (Заказы)'),
        ),
        migrations.AddField(
            model_name='forday',
            name='order_debt_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма наличными долга (Заказы)'),
        ),
        migrations.AddField(
            model_name='forday',
            name='order_debt_kaspi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма каспи долга (Заказы)'),
        ),
        migrations.AddField(
            model_name='forday',
            name='order_kaspi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма каспи (Заказы)'),
        ),
        migrations.AddField(
            model_name='forday',
            name='order_realization_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма наличными (Заказы под реализацию)'),
        ),
        migrations.AddField(
            model_name='forday',
            name='order_realization_debt_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма наличными долга (Заказы под реализацию)'),
        ),
        migrations.AddField(
            model_name='forday',
            name='order_realization_debt_kaspi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма каспи долга (Заказы под реализацию)'),
        ),
        migrations.AddField(
            model_name='forday',
            name='order_realization_kaspi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Сумма каспи (Заказы под реализацию)'),
        ),
    ]
