# Generated by Django 4.0.2 on 2022-03-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_statistics', '0005_delete_formonth_delete_forweek_delete_foryear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forday',
            name='order_realization_debt_cash',
        ),
    ]
