# Generated by Django 4.0.2 on 2022-02-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shopbuyer_customer_alter_shopbuyer_deliveryman'),
        ('users', '0002_deliveryman_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='shops',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_shops', to='shops.ShopBuyer', verbose_name='Магазины'),
        ),
    ]
