# Generated by Django 4.0.2 on 2022-10-10 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halal_site', '0005_remove_restaurant_gis_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товаров',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Наименование')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d/', verbose_name='Изображение')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.categoryproduct', verbose_name='Категория')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halal_site.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OpenningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, choices=[('MONDAY', 'Понедельник'), ('TUESDAY', 'Вторник'), ('WEDNESDAY', 'Среда'), ('THURSDAY', 'Четверг'), ('FRIDAY', 'Пятница'), ('SATURDAY', 'Суббота'), ('SUNDAY', 'Воскресенье')], default='Не выбрано', max_length=30, verbose_name='День')),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halal_site.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gis', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка в 2GIS ')),
                ('googlemaps', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка в Google карта')),
                ('yandexmaps', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка в Yandex карта')),
                ('applemaps', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка в Apple карта')),
                ('instagram', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка в Instagram')),
                ('facebook', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка в Facebook')),
                ('own_site', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на личный сайт')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halal_site.restaurant', verbose_name='Заведение')),
            ],
            options={
                'verbose_name': 'Ссылки заведения',
                'verbose_name_plural': 'Ссылки заведений',
            },
        ),
    ]
