# Generated by Django 4.0.2 on 2022-10-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_site', '0005_remove_restaurant_gis_link_and_more'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='RestaurantProduct',
        ),
    ]
