# Generated by Django 4.0.2 on 2022-10-10 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_product_restaurantproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantproduct',
            name='slug',
        ),
    ]
