# Generated by Django 4.0.2 on 2022-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_restaurantproduct_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Показывать?'),
        ),
        migrations.AddField(
            model_name='restaurantproduct',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Показывать?'),
        ),
    ]
