# Generated by Django 4.0.2 on 2022-10-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активность'),
        ),
    ]
