# Generated by Django 4.0.2 on 2022-10-25 08:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Улица, Дом (Квартира)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_cancelled', 'Заказ отменен'), ('completed', 'Заказ выполнен')], default='new', max_length=100, null=True, verbose_name='Статус заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CSRF Token'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_products',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[('le', 'Юр. лицо'), ('pe', 'Физ. лицо')], default='pe', max_length=100, null=True, verbose_name='Тип плательщика'),
        ),
    ]
