# Generated by Django 4.0.2 on 2022-10-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Анонимный пользователь'),
        ),
    ]
