# Generated by Django 4.0.2 on 2022-10-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Моб. телефон'),
        ),
    ]
