# Generated by Django 4.0.2 on 2022-10-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addition', '0001_initial'),
        ('orders', '0009_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='Улица, Дом (Квартира)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addition.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.paymenttype', verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person',
            field=models.CharField(max_length=250, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Моб. телефон'),
        ),
    ]
