# Generated by Django 4.0.2 on 2022-02-11 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('role', models.CharField(blank=True, choices=[('customer', 'Покупатель'), ('deliveryman', 'Доставщик'), ('shop_administrator', 'Администратор')], default='customer', max_length=100, verbose_name='Роль')),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Итоговая сумма')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Итоговая сумма')),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='carts.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзинах',
            },
        ),
    ]
