# Generated by Django 4.0.2 on 2022-04-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Себестоимость')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Тех. карта продукта',
                'verbose_name_plural': 'Тех. карты продуктов',
            },
        ),
    ]
