# Generated by Django 4.0.2 on 2022-04-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_techcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCardIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Брутто')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Себестоимость')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient', verbose_name='Ингредиент')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.techcard', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ингредиенты продукта',
                'verbose_name_plural': 'Ингредиенты продуктов',
            },
        ),
    ]
