# Generated by Django 4.0.2 on 2022-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_techcardingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена'),
        ),
    ]
