# Generated by Django 4.0.2 on 2022-04-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_ingredient_qty_alter_ingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Количество'),
        ),
    ]
