# Generated by Django 4.0.2 on 2022-04-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_ingredient_price_alter_ingredient_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('kg', 'кг'), ('gr', 'гр'), ('pc', 'шт'), ('l', 'л'), ('ml', 'мл')], default='kg', max_length=100, verbose_name='Ед. измерения'),
        ),
    ]
