# Generated by Django 4.0.2 on 2022-04-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_underingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underingredient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient', verbose_name='Продукт'),
        ),
    ]
