# Generated by Django 4.0.2 on 2022-04-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_underingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underingredient',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('gr', 'гр'), ('pc', 'шт'), ('ml', 'мл')], default='gr', max_length=100, verbose_name='Ед. измерения'),
        ),
    ]
