# Generated by Django 4.0.2 on 2022-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_underingredient_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underingredient',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='underingredient',
            name='gross',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Брутто'),
        ),
    ]
