# Generated by Django 4.0.2 on 2022-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_underingredient_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Себестоимость'),
        ),
    ]
