# Generated by Django 4.0.2 on 2022-04-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_ingredient_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcardingredient',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('gr', 'гр'), ('pc', 'шт'), ('ml', 'мл')], default='gr', max_length=100, verbose_name='Ед. измерения'),
        ),
    ]
