# Generated by Django 4.0.2 on 2022-02-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=20, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес магазина')),
                ('email', models.EmailField(max_length=254, verbose_name='Email магазина')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона магазина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания магазина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shopadministrator', verbose_name='Администратор магазина')),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.deliveryman', verbose_name='Доставщик')),
            ],
            options={
                'verbose_name': 'Закупщик',
                'verbose_name_plural': 'Закупщики',
            },
        ),
    ]
