# Generated by Django 4.0.2 on 2022-02-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopbuyer',
            name='email',
        ),
        migrations.AddField(
            model_name='shopbuyer',
            name='iin_bin',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИИН/БИН Магазина'),
        ),
        migrations.AlterField(
            model_name='shopbuyer',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес магазина'),
        ),
        migrations.AlterField(
            model_name='shopbuyer',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.shopadministrator', verbose_name='Администратор магазина'),
        ),
        migrations.AlterField(
            model_name='shopbuyer',
            name='deliveryman',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.deliveryman', verbose_name='Доставщик'),
        ),
        migrations.AlterField(
            model_name='shopbuyer',
            name='phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='Номер телефона магазина'),
        ),
        migrations.AlterField(
            model_name='shopbuyer',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Название магазина'),
        ),
    ]
