# Generated by Django 4.0.2 on 2022-02-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopbuyer_gis_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopbuyer',
            name='kaspi_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Имя каспи переводящего'),
        ),
    ]
