# Generated by Django 3.1.6 on 2021-12-04 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasOfEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код специальности')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название области образования')),
            ],
            options={
                'verbose_name': 'Область образования',
                'verbose_name_plural': '09) Области образования',
            },
        ),
        migrations.CreateModel(
            name='AreasOfTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код специальности')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название направления подготовки')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': '10) Направления подготовки',
            },
        ),
        migrations.CreateModel(
            name='CategoryUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория ВУЗа',
                'verbose_name_plural': '01) Категории ВУЗа',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': '04) Города',
            },
        ),
        migrations.CreateModel(
            name='EducationalPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название образовательной программы')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код специальности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Цель образовательной программы')),
                ('languages_of_instruction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Языки обучения')),
                ('duration_of_training', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок обучения')),
                ('volume_of_loans', models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем кредитов')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена за год')),
            ],
            options={
                'verbose_name': 'Образовательная программа',
                'verbose_name_plural': '12) Образовательные программы',
            },
        ),
        migrations.CreateModel(
            name='GroupsOfEducationalPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название группы образовательных программ')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код специальности')),
            ],
            options={
                'verbose_name': 'Группа образовательной программы',
                'verbose_name_plural': '11) Группы образовательных программ',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название области')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': '03) Области',
            },
        ),
        migrations.CreateModel(
            name='ScientificDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Академическая степень')),
            ],
            options={
                'verbose_name': 'Академическая степень',
                'verbose_name_plural': '06) Академические степени',
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название специальности')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': '08) Специальности',
            },
        ),
        migrations.CreateModel(
            name='TypeUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип ВУЗа',
                'verbose_name_plural': '02) Типы ВУЗа',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аббревиатура')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ВУЗа')),
                ('threshold_score', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пороговый балл для поступления')),
                ('qty_dormitories', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество общежитий')),
                ('old_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Старые названия')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/university/logo/', verbose_name='Логотип')),
                ('background', models.ImageField(blank=True, null=True, upload_to='image/university/background/', verbose_name='Фон')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'ВУЗ',
                'verbose_name_plural': '05) ВУЗы',
            },
        ),
        migrations.CreateModel(
            name='UNTSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия предметов')),
            ],
            options={
                'verbose_name': 'Профильные предметы на ЕНТ',
                'verbose_name_plural': '07) Профильные предметы на ЕНТ',
            },
        ),
        migrations.CreateModel(
            name='UniversitySpecializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.specializations', verbose_name='Специальность')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.university', verbose_name='ВУЗ')),
            ],
            options={
                'verbose_name': 'Специальность университета',
                'verbose_name_plural': '13) Специальности университетов',
            },
        ),
        migrations.CreateModel(
            name='UniversityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/university/news/photo/', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Новость университета',
                'verbose_name_plural': 'Новости университетов',
            },
        ),
        migrations.CreateModel(
            name='UniversityGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/university/photo/', verbose_name='Картинка')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Фотография университета',
                'verbose_name_plural': 'Фотографии университетов',
            },
        ),
        migrations.CreateModel(
            name='UniversityContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона 1')),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона 2')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Контакты университета',
                'verbose_name_plural': 'Контакты университетов',
            },
        ),
    ]
