# Generated by Django 3.1.6 on 2021-12-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('educational_institutions', '0002_auto_20211204_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsForAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.educationalprograms', verbose_name='Образовательная программа')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Студент')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.university', verbose_name='ВУЗ')),
            ],
            options={
                'verbose_name': 'Заявка на поступление',
                'verbose_name_plural': '14) Заявки на поступления',
            },
        ),
    ]
