# Generated by Django 3.1 on 2020-08-08 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0003_auto_20200808_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productbordercolor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productmaterialcolor'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productthreadcolor'),
        ),
    ]
