# Generated by Django 3.1 on 2020-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200809_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
