# Generated by Django 3.1 on 2020-08-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступный?'),
        ),
    ]
