# Generated by Django 3.1 on 2020-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200809_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена в рублях', max_digits=10, null=True, verbose_name='Цена'),
        ),
    ]
