# Generated by Django 3.1 on 2020-08-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200809_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
