# Generated by Django 3.1 on 2020-08-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200810_0304'),
        ('orders', '0011_auto_20200809_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productaccessory', verbose_name='Аксессуар товара'),
        ),
    ]
