# Generated by Django 3.1 on 2020-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_productinbasket_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступный?'),
        ),
    ]
