# Generated by Django 3.1 on 2020-08-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_productinbasket_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
