# Generated by Django 3.1 on 2020-08-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200814_1019'),
        ('orders', '0021_auto_20200813_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='product_border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basket_items', to='shop.productbordercolor', verbose_name='Цвет окантовки товара'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product_border',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productbordercolor', verbose_name='Цвет окантовки товара'),
        ),
    ]
