# Generated by Django 4.0.2 on 2022-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_article_alter_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': '8) Виды товаров',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_p',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_category_p', to='products.CategoryProduct', verbose_name='Вид товара'),
        ),
    ]
