# Generated by Django 4.0.2 on 2022-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categoryproduct_product_category_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_p',
            field=models.ManyToManyField(blank=True, related_name='related_category_p', to='products.CategoryProduct', verbose_name='Вид товара'),
        ),
    ]
