# Generated by Django 4.0.2 on 2022-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_all',
            field=models.ManyToManyField(blank=True, related_name='related_category_all', to='products.Category', verbose_name='Категори'),
        ),
    ]
