# Generated by Django 4.0.2 on 2022-11-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_category_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_all',
            field=models.ManyToManyField(blank=True, related_name='related_category_cat', to='products.Category', verbose_name='Категории'),
        ),
    ]
