# Generated by Django 4.0.2 on 2022-12-06 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_brand_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeedback',
            name='title',
        ),
        migrations.AddField(
            model_name='productfeedback',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AddField(
            model_name='productfeedback',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='productfeedback',
            name='for_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Анонимный пользователь'),
        ),
        migrations.AddField(
            model_name='productfeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
