# Generated by Django 4.0.2 on 2022-02-11 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryForDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата доставки')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доставка за день',
                'verbose_name_plural': 'Доставки за день',
            },
        ),
        migrations.CreateModel(
            name='ShopDeliveryForDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False, verbose_name='Доставлено')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата доставки')),
                ('delivery', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryforday', verbose_name='Доставка')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shopbuyer', verbose_name='Закупщик')),
            ],
            options={
                'verbose_name': 'Закупщик',
                'verbose_name_plural': 'Закупщики',
            },
        ),
    ]
