# Generated by Django 4.0.2 on 2022-02-04 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница о Дине',
                'verbose_name_plural': 'Страница о Дине',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страница о нас',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('in_order', models.BooleanField(default=False)),
                ('for_anonymous_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('in_order', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзинах',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=1000, verbose_name='Изображение')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя категории')),
                ('service', models.BooleanField(blank=True, default=False, verbose_name='Это услуга?')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории 3 уровень',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('type_of_request', models.CharField(choices=[('QUALITY_OF_SERVICE', 'Качество обслуживания'), ('LONG_SERVICE_LIFE', 'Долгое обслуживание'), ('DEFECTIVE_PRODUCT', 'Бракованный товар'), ('LATE_DELIVERY', 'Несвоевременная доставка'), ('NON_CORRECT_PRODUCT_DESCRIPTION', 'Неккоректное описание товара'), ('THE_QUALITY_OF_THE_PRODUCT', 'Качество товара')], max_length=100, verbose_name='Тип обращения')),
                ('comment', models.TextField(verbose_name='Комментарий к жалобе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('sex', models.CharField(blank=True, choices=[('MEN', 'Мужчина'), ('WOMEN', 'Женщина')], default='Нет', max_length=30, verbose_name='Пол')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('job', models.CharField(blank=True, choices=[('DIRECTOR', 'Директор'), ('SELLER', 'Продавец'), ('REPAIRER', 'Ремонтник'), ('ACCOUNTANT', 'Бухгалтер')], max_length=30, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='MiddleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=1000, verbose_name='Изображение')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя категории')),
                ('service', models.BooleanField(blank=True, default=False, verbose_name='Это услуга?')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории 2 уровень',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('image', models.ImageField(upload_to='news/img/', verbose_name='Фото')),
                ('slug', models.SlugField()),
                ('content', models.TextField(verbose_name='Контент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('in_progress', 'Заказ в обработке'), ('is_cancelled', 'Заказ отменен'), ('completed', 'Заказ выполнен')], default='new', max_length=100, verbose_name='Статус заказ')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], default='self', max_length=100, verbose_name='Тип заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderForShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(blank=True, default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('status', models.CharField(choices=[('STATUS_NEW', 'Новый заказ'), ('STATUS_IN_PROGRESS', 'Заказ в обработке'), ('STATUS_CANCELLED', 'Заказ отменен'), ('STATUS_COMPLETED', 'Заказ выполнен')], default='STATUS_NEW', max_length=100, verbose_name='Статус заказ')),
            ],
            options={
                'verbose_name': 'Заказ (для продавца)',
                'verbose_name_plural': 'Заказы (для продавца)',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В обработке'), ('is_cancelled', 'Отменен'), ('completed', 'Выполнен')], default='new', max_length=100, verbose_name='Статус заказ')),
            ],
            options={
                'verbose_name': 'Товар (для заказа)',
                'verbose_name_plural': 'Товары (для заказа)',
            },
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=1000, verbose_name='Изображение')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Имя категории')),
                ('service', models.BooleanField(blank=True, default=False, verbose_name='Это услуга?')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории 1 уровень',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('status', models.CharField(choices=[('ON_VERIFICATION', 'На проверке'), ('ACTIVE', 'Активный'), ('NO_ACTIVE', 'Не активный')], default='На проверке', max_length=30, verbose_name='Статус')),
                ('status_product', models.CharField(blank=True, choices=[('IN_STOCK', 'В наличии'), ('OUT_OF_STOCK', 'Не в наличии'), ('WILL_BE_SOON', 'Скоро будет')], default='В наличии', max_length=30, verbose_name='В наличии')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Изображение 3')),
                ('image_4', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Изображение 4')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('contractual_price', models.BooleanField(blank=True, default=False, verbose_name='Договорная цена')),
                ('service', models.BooleanField(blank=True, default=False, verbose_name='Это услуга?')),
                ('order_qty', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='slider/', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, db_index=True, max_length=255, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=1000, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Секретно',
                'verbose_name_plural': 'Секретно',
            },
        ),
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('type_of_request', models.CharField(choices=[('QUALITY_OF_SERVICE', 'Качество обслуживания'), ('LONG_SERVICE_LIFE', 'Долгое обслуживание'), ('DEFECTIVE_PRODUCT', 'Бракованный товар'), ('LATE_DELIVERY', 'Несвоевременная доставка'), ('NON_CORRECT_PRODUCT_DESCRIPTION', 'Неккоректное описание товара'), ('THE_QUALITY_OF_THE_PRODUCT', 'Качество товара')], max_length=100, verbose_name='Тип обращения')),
                ('comment', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_support', to='mainapp.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Служба поддержки',
                'verbose_name_plural': 'Служба поддержки',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(db_index=True, max_length=20, verbose_name='Название магазина')),
                ('status', models.CharField(choices=[('ON_VERIFICATION', 'На проверке'), ('ACTIVE', 'Активный'), ('NO_ACTIVE', 'Не активный')], default='На проверке', max_length=30, verbose_name='Статус')),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='shop/logo/', verbose_name='Логотип магазина')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('slug', models.SlugField()),
                ('shop_address', models.CharField(max_length=255, verbose_name='Адрес магазина')),
                ('shop_email', models.EmailField(max_length=254, verbose_name='Email магазина')),
                ('shop_phone', models.CharField(max_length=12, verbose_name='Номер телефона магазина')),
                ('instagram', models.CharField(blank=True, max_length=250, verbose_name='Имя пользователя в Instagram')),
                ('vk', models.CharField(blank=True, max_length=250, verbose_name='Имя пользователя в VK')),
                ('facebook', models.CharField(blank=True, max_length=250, verbose_name='Имя пользователя в Facebook')),
                ('whatsapp', models.CharField(blank=True, max_length=12, verbose_name='Номер телефона WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя в Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания магазина')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания срока магазина')),
                ('category', models.ManyToManyField(blank=True, to='mainapp.ParentCategory', verbose_name='Категории магазина')),
                ('customer', models.ManyToManyField(blank=True, to='mainapp.Customer', verbose_name='Администраторы магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Сообщение')),
                ('created_at_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='RequestToWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30, verbose_name='Должность')),
                ('yes_or_no', models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=30, verbose_name='Ответ')),
                ('active', models.BooleanField(blank=True, default=False, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания запроса')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Кому')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop', verbose_name='От кого')),
            ],
            options={
                'verbose_name': 'Запрос на работу',
                'verbose_name_plural': 'Запросы на работу',
            },
        ),
        migrations.CreateModel(
            name='RequestServiceToShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новая заявка'), ('in_progress', 'Заявка в обработке'), ('is_cancelled', 'Заявка отменена'), ('completed', 'Заявка выполнена')], default='new', max_length=100, verbose_name='Статус заказ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пользователь')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Услуга')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заявка на услугу для магазина',
                'verbose_name_plural': 'Заявки на услуги для магазина',
            },
        ),
        migrations.CreateModel(
            name='RequestFromShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('shop_name', models.CharField(db_index=True, max_length=20, verbose_name='Название магазина')),
                ('shop_address', models.CharField(max_length=255, verbose_name='Адрес магазина')),
                ('shop_email', models.EmailField(max_length=254, verbose_name='Email магазина')),
                ('shop_phone', models.CharField(max_length=15, verbose_name='Номер телефона магазина')),
                ('status', models.CharField(choices=[('new', 'Новый заявка'), ('in_progress', 'Заявка в обработке'), ('is_cancelled', 'Заявка отменен'), ('completed', 'Заявка выполнен')], default='new', max_length=100, verbose_name='Статус заявки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('category', models.ManyToManyField(blank=True, to='mainapp.ParentCategory', verbose_name='Категории магазина')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_req_f_sh', to='mainapp.customer', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на регистрацию',
                'verbose_name_plural': 'Заявки на регистрацию',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Оценка единица')),
                ('two', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Оценка двойка')),
                ('three', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Оценка тройка')),
                ('four', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Оценка четверка')),
                ('five', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Оценка пятерка')),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Средняя оценка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Рейтинг товара',
                'verbose_name_plural': 'Рейтинги товаров',
            },
        ),
    ]
