# Generated by Django 4.0.2 on 2022-11-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='banner/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
