# Generated by Django 4.0.2 on 2022-11-26 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_categorypublication_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypublication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, upload_to='publication/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
