# Generated by Django 4.0.2 on 2022-11-26 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_categorypublication_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_at_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
