# Generated by Django 4.0.2 on 2022-11-26 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_publication_created_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='created_at_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
