# Generated by Django 4.0.2 on 2022-11-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_publication_created_at_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='publication/', verbose_name='Изображение 2'),
        ),
    ]
