# Generated by Django 4.0.2 on 2022-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finish_making',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завершение оформления'),
        ),
    ]
