# Generated by Django 4.0.2 on 2022-02-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_finish_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, choices=[('kaspi', 'Каспи'), ('cash', 'Наличными')], default='customer', max_length=100, verbose_name='Оплата'),
        ),
    ]
