# Generated by Django 4.0.2 on 2022-02-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(blank=True, choices=[('kaspi', 'Каспи'), ('cash', 'Наличными')], default='cash', max_length=100, verbose_name='Оплата'),
        ),
    ]
