# Generated by Django 4.0.2 on 2022-02-12 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buying_type',
            field=models.CharField(blank=True, choices=[('simple', 'Обычный'), ('realization', 'Под реализацию')], default='simple', max_length=100, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата получения заказа'),
        ),
    ]
