# Generated by Django 4.0.2 on 2022-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_refund_refundproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
