# Generated by Django 4.0.2 on 2022-02-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0010_refund_finish_making'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparedProductsPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата изготовления')),
            ],
            options={
                'verbose_name': 'Заготовленный товар',
                'verbose_name_plural': 'Заготовленные товары',
            },
        ),
        migrations.CreateModel(
            name='PreparedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('prepared_products_p_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_product', to='orders.preparedproductsperday', verbose_name='Заготовленные товары')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар (Заготовленный товар)',
                'verbose_name_plural': 'Товары (Заготовленный товар)',
            },
        ),
    ]
