# Generated by Django 4.0.2 on 2022-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_preparedproductsperday_preparedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedproduct',
            name='prepared_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество заготовленных'),
        ),
        migrations.AlterField(
            model_name='preparedproduct',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Остаток не проданного'),
        ),
    ]
