# Generated by Django 4.0.2 on 2022-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_preparedproduct_prepared_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedproductsperday',
            name='prepared_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Общее количество заготовленных товаров'),
        ),
    ]
