# Generated by Django 4.0.2 on 2022-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_preparedproductsperday_prepared_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedproduct',
            name='sale_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проданного'),
        ),
    ]
