# Generated by Django 4.0.2 on 2022-02-20 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_preparedproduct_refund_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparedproductsperday',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата изготовления'),
        ),
    ]
