# Generated by Django 4.0.2 on 2022-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_preparedproductsperday_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(blank=True, default=False, verbose_name='Оплатил'),
        ),
    ]
