# Generated by Django 4.0.2 on 2022-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_order_buying_type_alter_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedproduct',
            name='stocks_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товаров по акции'),
        ),
    ]
