# Generated by Django 4.0.2 on 2022-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at_time',
            field=models.DateTimeField(auto_now_add=True, default=2, verbose_name='Дата создания заказа + время'),
            preserve_default=False,
        ),
    ]
