# Generated by Django 4.0.2 on 2022-02-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_created_at_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at_time',
        ),
    ]
