# Generated by Django 4.0.2 on 2022-03-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_remove_order_created_at_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparedproduct',
            name='action',
            field=models.CharField(blank=True, choices=[('plus', 'Прибавить'), ('minus', 'Отнять')], max_length=100, null=True, verbose_name='Действие'),
        ),
    ]
