# Generated by Django 4.0.2 on 2022-03-15 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shopbuyer_customer_alter_shopbuyer_deliveryman'),
        ('orders', '0026_preparedproduct_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_pay_invoice', to='orders.order', verbose_name='Заказ')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_pay_invoice', to='shops.shopbuyer', verbose_name='Закупщик')),
            ],
            options={
                'verbose_name': 'Счет на оплату',
                'verbose_name_plural': 'Счет на оплату',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='Номер')),
                ('created_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice', to='orders.order', verbose_name='Заказ')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_invoice', to='shops.shopbuyer', verbose_name='Закупщик')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
    ]
