# Generated by Django 4.0.2 on 2022-03-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_paymentinvoice_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер'),
        ),
    ]
