# Generated by Django 4.0.2 on 2022-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Нумерация'),
        ),
    ]
