# Generated by Django 4.0.2 on 2022-04-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        ('orders', '0029_orderproduct_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='order',
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Итоговая сумма'),
        ),
        migrations.CreateModel(
            name='OrdersPaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_pay_invoice', to='orders.order', verbose_name='Заказ')),
                ('pay_invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_invoice', to='orders.paymentinvoice', verbose_name='Счет на оплату')),
            ],
            options={
                'verbose_name': 'Счет на оплату (Заказы)',
                'verbose_name_plural': 'Счет на оплату (Заказы)',
            },
        ),
        migrations.CreateModel(
            name='OrderProductPaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Нумерация')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Итоговая сумма')),
                ('pay_invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pay_invoice', to='orders.paymentinvoice', verbose_name='Счет на оплату')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
