# Generated by Django 4.0.2 on 2022-04-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_orderproductpaymentinvoice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='finish_making',
            field=models.BooleanField(blank=True, default=False, verbose_name='Завершение оформления'),
        ),
    ]
