# Generated by Django 4.0.2 on 2022-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_paymentinvoice_finish_making'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductpaymentinvoice',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Нумерация'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Номер'),
        ),
    ]
