# Generated by Django 4.0.2 on 2022-04-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_orderproductpaymentinvoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductpaymentinvoice',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
