# Generated by Django 4.0.2 on 2022-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_orderproductpaymentinvoice_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='number_2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Номер договора'),
        ),
    ]
