# Generated by Django 4.0.2 on 2022-11-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_warranty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutCompany',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Warranty',
        ),
    ]
