# Generated by Django 3.1.6 on 2021-12-04 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educational_institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название теста')),
                ('all_question', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Всего вопросов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания теста')),
                ('unt_subjects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_institutions.untsubjects', verbose_name='Профильные предметы на ЕНТ')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ')),
                ('correct', models.BooleanField(blank=True, default=False, verbose_name='Правильный?')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('knowledge_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgetests.knowledgetest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserAnswersForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.BooleanField(blank=True, default=False, verbose_name='Правильно ответил?')),
                ('isnt_answer', models.BooleanField(blank=True, default=False, verbose_name='Не ответил?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест (для пользователя)',
                'verbose_name_plural': 'Тесты (для пользователя)',
            },
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('finish', models.BooleanField(blank=True, default=False, verbose_name='Завершен?')),
                ('all_question', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Всего вопросов')),
                ('finish_question', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Правильно отвечены')),
                ('knowledge_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgetests.knowledgetest', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('user_answer', models.ManyToManyField(blank=True, to='knowledgetests.UserAnswersForTest', verbose_name='Ответы')),
            ],
            options={
                'verbose_name': 'Тест (для пользователя)',
                'verbose_name_plural': 'Тесты (для пользователя)',
            },
        ),
        migrations.AddField(
            model_name='useranswersfortest',
            name='user_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgetests.usertest', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='useranswersfortest',
            name='user_test_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgetests.questionanswers', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='useranswersfortest',
            name='user_test_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledgetests.testquestions', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionanswers',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgetests.testquestions', verbose_name='Вопрос'),
        ),
    ]
