# Generated by Django 4.0.2 on 2022-10-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
    ]
