# Generated by Django 4.0.2 on 2022-10-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halal_site', '0002_alter_supplier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurant/logo/', verbose_name='Изображение'),
        ),
    ]
