# Generated by Django 4.0.2 on 2022-10-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halal_site', '0003_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория (Заведение)',
                'verbose_name_plural': 'Категории (Заведение)',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halal_site.categoryrestaurant', verbose_name='Категория'),
        ),
    ]
