# Generated by Django 4.0.2 on 2022-10-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halal_site', '0004_categoryrestaurant_restaurant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='gis_link',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='work_schedule',
        ),
    ]
