# Generated by Django 3.1 on 2020-08-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProductAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название категории для аксессуара товара')),
            ],
            options={
                'verbose_name': 'Категория для аксессуара товара',
                'verbose_name_plural': 'Категории для аксессуара товара',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название товара')),
                ('slug', models.SlugField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Цена в рублях', max_digits=10, verbose_name='Цена товара')),
                ('price_old', models.DecimalField(decimal_places=2, default=0, help_text='Цена в рублях', max_digits=10, verbose_name='Старая цена товара')),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото товара')),
                ('available', models.BooleanField(default=True, verbose_name='Доступный?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['created'],
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductThreadColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(max_length=150, verbose_name='Название цвета')),
                ('color_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото цвета')),
                ('product_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цвет нити товара',
                'verbose_name_plural': 'Цвета нити товара',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterialColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(max_length=150, verbose_name='Название цвета')),
                ('color_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото цвета')),
                ('product_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цвет материала товара',
                'verbose_name_plural': 'Цвета материала товара',
            },
        ),
        migrations.CreateModel(
            name='ProductBorderColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(max_length=150, verbose_name='Название цвета')),
                ('color_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото цвета')),
                ('product_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото товара')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цвет оконтовки товара',
                'verbose_name_plural': 'Цвета окантовки товара',
            },
        ),
        migrations.CreateModel(
            name='ProductAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_title', models.CharField(max_length=150, verbose_name='Название аксессуара')),
                ('accessory_price', models.IntegerField(verbose_name='Цена')),
                ('accessory_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото аксессуара')),
                ('product_img', models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Фото аксессуара на товаре')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categoryproductaccessory', verbose_name='Категория аксессуара')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Аксессуар товара',
                'verbose_name_plural': 'Аксессуары товара',
            },
        ),
    ]
