# Generated by Django 3.1 on 2020-08-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200809_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaccessory',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступный?'),
        ),
        migrations.AddField(
            model_name='productbordercolor',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступный?'),
        ),
        migrations.AddField(
            model_name='productmaterialcolor',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступный?'),
        ),
        migrations.AddField(
            model_name='productthreadcolor',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступный?'),
        ),
    ]
