# Generated by Django 3.1 on 2020-08-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200810_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productaccessory',
            name='accessory_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото аксессуара'),
        ),
        migrations.AlterField(
            model_name='productaccessory',
            name='product_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото аксессуара на товаре'),
        ),
        migrations.AlterField(
            model_name='productbordercolor',
            name='color_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productbordercolor',
            name='product_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productmaterialcolor',
            name='color_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productmaterialcolor',
            name='product_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productthreadcolor',
            name='color_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productthreadcolor',
            name='product_img',
            field=models.ImageField(blank=True, default='/static/images/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
