# Generated by Django 3.1 on 2020-08-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200811_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccessory',
            name='product_img',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото аксессуара на товаре'),
        ),
    ]
