# Generated by Django 3.1 on 2020-08-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200811_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productbordercolor',
            name='color_img',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productbordercolor',
            name='product_img',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productmaterialcolor',
            name='color_img',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productmaterialcolor',
            name='product_img',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productthreadcolor',
            name='color_img',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productthreadcolor',
            name='product_img',
            field=models.ImageField(blank=True, default='default/img_p.png', upload_to='product/%Y/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
