# Generated by Django 3.1 on 2020-08-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200811_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbordercolor',
            options={'verbose_name': 'Цвет окантовки товара', 'verbose_name_plural': 'Цвета окантовки товара'},
        ),
    ]
