# Generated by Django 3.1 on 2020-08-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200814_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproductaccessory',
            name='product',
            field=models.ManyToManyField(null=True, to='shop.Product'),
        ),
    ]
