# Generated by Django 3.1 on 2020-08-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200814_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductaccessory',
            name='product',
            field=models.ManyToManyField(blank=True, to='shop.Product', verbose_name='Товары где будут использоваться аксессуар'),
        ),
    ]
