# Generated by Django 3.1 on 2020-08-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200815_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproductaccessory',
            name='product',
            field=models.ManyToManyField(to='shop.Product', verbose_name='Товары где будут использоваться аксессуар'),
        ),
    ]
