# Generated by Django 4.0.2 on 2022-04-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category'),
        ('menu', '0015_techcardingredient_unit_of_measurement'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент (Склад)', 'verbose_name_plural': 'Ингредиенты (Склад)'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('kg', 'кг'), ('gr', 'гр'), ('pc', 'шт'), ('l', 'л'), ('ml', 'мл')], default='kg', max_length=100, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='Итого')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Продукт')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Продукт (Склад)',
                'verbose_name_plural': 'Продукты (Склад)',
            },
        ),
    ]
