# Generated by Django 3.1 on 2020-08-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200812_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='image/logo/', verbose_name='Иконка сайта')),
            ],
            options={
                'verbose_name': 'SEO сайта',
                'verbose_name_plural': 'SEO сайта',
            },
        ),
    ]
