# Generated by Django 3.1 on 2020-08-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='google_analytics',
            field=models.TextField(blank=True, verbose_name='Google Analytics'),
        ),
    ]
