# Generated by Django 3.1 on 2020-08-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_seo_google_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='google_analytics',
            field=models.TextField(blank=True, null=True, verbose_name='Google Analytics'),
        ),
    ]
