# Generated by Django 3.1.1 on 2020-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20200813_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default='', max_length=50, verbose_name='Тема'),
        ),
    ]
