# Generated by Django 3.1.1 on 2020-09-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_contactform_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
    ]
